### ISSUE TITLE
Output isn't being sent to the csv file

### ISSUE THREAD

**Issue by alexado128** [christophe-garon/Linkedin-Post-Scraper#1]
Basing my own code off yours, I tried executing the file in Ubuntu but was unable to see the results in the csv file. There were no errors found in the code itself, so I was wondering if there were any suggestions in being able to see the webscraped-data in the csv. The csv file itself can open, but all I see are the headings "Date Posted, Media Type, Post Text, etc"
edit: I tried debugging the code, and found that the problem is that the lists don't have any values in them, despite my appending the HTML element(s) found to them prior to calling the pandas dataframe on it

**Comment by christophe-garon** [comment]
hey thanks for letting me know about the bug. Linkedin updates their html structure occasionally so that is what the issue was. I updated the tags and it should be working now.
